name: 一键全部构建

on:
  workflow_dispatch:

  schedule:
    - cron: '0 4 * * 2'
    
jobs:
  build_11r:
    uses: ./.github/workflows/sm8475-11r.yml
  build_12r:
    uses: ./.github/workflows/sm8550-12r.yml
  build_ace2pro:
    uses: ./.github/workflows/sm8550-ace2pro.yml
  build_ace2pro_t:
    uses: ./.github/workflows/sm8550-ace2pro_t.yml
  build_ace3:
    uses: ./.github/workflows/sm8550-ace3.yml
